// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	UserLoginByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
